cluster_name: "${cluster_name}"
bootstrap_url: "http://${bootstrap_ip}:${bootstrap_port}"
master_discovery: master_http_loadbalancer
ip_detect_public_filename: "genconf/ip-detect-public"
exhibitor_address: "${master_elb_dns_address}"
exhibitor_storage_backend: aws_s3
aws_region: "${region}"
s3_bucket: "${s3_bucket}"
s3_prefix: "${cluster_id}"
exhibitor_explicit_keys: false
enable_docker_gc: true
num_masters: "${number_of_masters}"
resolvers:
  # AWS internal nameserver
  #
  # The first IP address in this list is the AWS internal nameserver. It is needed for some frameworks
  # that use internal hostnames. Using this IP address will allow you to reach your nodes by their internal
  # hostname like this: ip-10-0-0-0.eu-west-1.compute.internal.
  #
  # Docs: http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-dns.html#vpc-dns-support
  - 169.254.169.253
  - 8.8.8.8
  - 8.8.4.4
